---
title: Jekyll-Uno
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: Jekyll-Uno - a minimal, responsive theme for Jekyll
url: http://bookersoftware.eu
author:
  name: Tim Booker
  email: tim@bookersoftware.eu
  twitter_username: timbooker
  facebook_username: booker.tim
  github_username: timbooker
  linkedin_username: timothybooker
destination: _site
paginate: 10
permalink: "/:year/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
gems:
- jekyll-paginate
exclude:
- README.md
- Gemfile
- Gemfile.lock
- screenshot.png
